'use client';
  // This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { jsx, jsxs, Fragment } from 'react/jsx-runtime';
import { Text, Link, useSitecore, Placeholder, NextImage, RichText, withDatasourceCheck, Image, AppPlaceholder, CdpHelper } from '@sitecore-content-sdk/nextjs';
import useVisibility from 'src/hooks/useVisibility';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Autoplay, EffectCoverflow, Pagination, Navigation } from 'swiper/modules';
import { CountUp } from 'components/non-sitecore/CountUp';
import { DottedAccent } from 'components/non-sitecore/DottedAccent';
import { useState, useEffect, useCallback, useRef } from 'react';
import React from 'react';
import { ParallaxBackgroundImage } from 'components/non-sitecore/ParallaxBackgroundImage';
import Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 from 'next/link';
import { FacebookIcon, FacebookShareButton, LinkedinIcon, LinkedinShareButton, TwitterIcon, TwitterShareButton } from 'react-share';
import Head from 'next/head';
import { ParallaxBanner, useParallax, Parallax } from 'react-scroll-parallax';
import { IconAccent } from 'components/non-sitecore/IconAccent';
import client from 'src/lib/sitecore-client';
import { pageView } from '@sitecore-content-sdk/events';
import config from 'sitecore.config';

const importMap = [
  {
    module: 'react/jsx-runtime',
    exports: [
      { name: 'jsx', value: jsx },
      { name: 'jsxs', value: jsxs },
      { name: 'Fragment', value: Fragment },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Text', value: Text },
      { name: 'Link', value: Link },
      { name: 'useSitecore', value: useSitecore },
      { name: 'Placeholder', value: Placeholder },
      { name: 'NextImage', value: NextImage },
      { name: 'RichText', value: RichText },
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
      { name: 'Image', value: Image },
      { name: 'AppPlaceholder', value: AppPlaceholder },
      { name: 'CdpHelper', value: CdpHelper },
    ]
  },
  {
    module: 'src/hooks/useVisibility',
    exports: [
      { name: 'default', value: useVisibility },
    ]
  },
  {
    module: 'swiper/react',
    exports: [
      { name: 'Swiper', value: Swiper },
      { name: 'SwiperSlide', value: SwiperSlide },
    ]
  },
  {
    module: 'swiper/modules',
    exports: [
      { name: 'Autoplay', value: Autoplay },
      { name: 'EffectCoverflow', value: EffectCoverflow },
      { name: 'Pagination', value: Pagination },
      { name: 'Navigation', value: Navigation },
    ]
  },
  {
    module: 'components/non-sitecore/CountUp',
    exports: [
      { name: 'CountUp', value: CountUp },
    ]
  },
  {
    module: 'components/non-sitecore/DottedAccent',
    exports: [
      { name: 'DottedAccent', value: DottedAccent },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useState', value: useState },
      { name: 'useEffect', value: useEffect },
      { name: 'useCallback', value: useCallback },
      { name: 'useRef', value: useRef },
      { name: 'default', value: React },
    ]
  },
  {
    module: 'components/non-sitecore/ParallaxBackgroundImage',
    exports: [
      { name: 'ParallaxBackgroundImage', value: ParallaxBackgroundImage },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 },
    ]
  },
  {
    module: 'react-share',
    exports: [
      { name: 'FacebookIcon', value: FacebookIcon },
      { name: 'FacebookShareButton', value: FacebookShareButton },
      { name: 'LinkedinIcon', value: LinkedinIcon },
      { name: 'LinkedinShareButton', value: LinkedinShareButton },
      { name: 'TwitterIcon', value: TwitterIcon },
      { name: 'TwitterShareButton', value: TwitterShareButton },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'react-scroll-parallax',
    exports: [
      { name: 'ParallaxBanner', value: ParallaxBanner },
      { name: 'useParallax', value: useParallax },
      { name: 'Parallax', value: Parallax },
    ]
  },
  {
    module: 'components/non-sitecore/IconAccent',
    exports: [
      { name: 'IconAccent', value: IconAccent },
    ]
  },
  {
    module: 'src/lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: '@sitecore-content-sdk/events',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultImportEntries, importMap);
